"""Русские названия мобов и предметов (vanilla)."""

MOB_NAMES_RU: dict[str, str] = {
    "allay": "Аллей",
    "armadillo": "Броненосец",
    "axolotl": "Аксолotl",
    "bat": "Летучая мышь",
    "bee": "Пчела",
    "blaze": "Ифрит (Blaze)",
    "bogged": "Болотник",
    "breeze": "Бриз",
    "camel": "Верблюд",
    "cat": "Кошка",
    "cave spider": "Пещерный паук",
    "chicken": "Курица",
    "cod": "Треска",
    "cow": "Корова",
    "creeper": "Крипер",
    "dolphin": "Дельфин",
    "donkey": "Осёл",
    "drowned": "Утопленник",
    "elder guardian": "Древний страж",
    "ender dragon": "Дракон Края",
    "enderman": "Эндермен",
    "endermite": "Эндермит",
    "evoker": "Заклинатель",
    "fox": "Лиса",
    "frog": "Лягушка",
    "ghast": "Гаст",
    "glow squid": "Светящийся спрут",
    "goat": "Коза",
    "guardian": "Страж",
    "hoglin": "Хоглин",
    "horse": "Лошадь",
    "husk": "Кадавр",
    "iron golem": "Железный голем",
    "llama": "Лама",
    "magma cube": "Лавовый куб",
    "mooshroom": "Муушрум",
    "mule": "Мул",
    "ocelot": "Оцелот",
    "panda": "Панда",
    "parrot": "Попугай",
    "phantom": "Фантом",
    "pig": "Свинья",
    "piglin": "Пиглин",
    "piglin brute": "Брутальный пиглин",
    "pillager": "Разбойник",
    "polar bear": "Белый медведь",
    "pufferfish": "Иглобрюх",
    "rabbit": "Кролик",
    "ravager": "Разоритель",
    "salmon": "Лосось",
    "sheep": "Овца",
    "shulker": "Шалкер",
    "silverfish": "Чешуйница",
    "skeleton": "Скелет",
    "slime": "Слайм",
    "sniffer": "Нюхач",
    "snow golem": "Снежный голем",
    "spider": "Паук",
    "squid": "Спрут",
    "stray": "Зимогор",
    "strider": "Страйдер",
    "tadpole": "Головастик",
    "trader llama": "Лама торговца",
    "tropical fish": "Тропическая рыба",
    "turtle": "Черепаха",
    "vex": "Досаждатель",
    "villager": "Житель",
    "vindicator": "Поборник",
    "wandering trader": "Странствующий торговец",
    "warden": "Warden",
    "witch": "Ведьма",
    "wither": "Иссушитель",
    "wither skeleton": "Скелет-иссушитель",
    "wolf": "Волк",
    "zoglin": "Зоглин",
    "zombie": "Зомби",
    "zombie villager": "Зомби-житель",
    "zombified piglin": "Зомби-пиглин",
}

ITEM_NAMES_RU: dict[str, str] = {
    "arrow": "Стрела",
    "baked potato": "Печёный картофель",
    "blaze rod": "Огненный стержень",
    "bone": "Кость",
    "carrot": "Морковь",
    "cooked mutton": "Жареная баранина",
    "copper ingot": "Медный слиток",
    "ender pearl": "Жемчуг Эндера",
    "feather": "Перо",
    "ghast tear": "Слеза гаста",
    "glass bottle": "Пустая бутылка",
    "glowstone dust": "Светопыль",
    "gold nugget": "Золотой самородок",
    "gunpowder": "Порох",
    "iron ingot": "Железный слиток",
    "leather": "Кожа",
    "phantom membrane": "Мембрана фантома",
    "poppy": "Мак",
    "potato": "Картофель",
    "raw beef": "Сырая говядина",
    "raw chicken": "Сырое мясо курицы",
    "raw mutton": "Сырая баранина",
    "raw porkchop": "Сырая свинина",
    "raw rabbit": "Сырой кролик",
    "rabbit foot": "Кроличья лапка",
    "rabbit hide": "Кроличья шкурка",
    "redstone": "Редстоун",
    "rotten flesh": "Гнилая плоть",
    "sculk catalyst": "Sculk-катализатор",
    "slimeball": "Слизь",
    "spider eye": "Паучий глаз",
    "stick": "Палка",
    "string": "Нить",
    "sugar": "Сахар",
    "trident": "Трезубец",
    "wool": "Шерсть",
    "diamond": "Алмаз",
    "torch": "Факел",
    "crafting table": "Верстак",
    "diamond pickaxe": "Алмазная кирка",
}

RECIPE_NAMES_RU: dict[str, str] = {
    "diamond_pickaxe": "Алмазная кирка",
    "diamond": "Алмаз",
    "iron_ingot": "Железный слиток",
    "torch": "Факел",
    "crafting_table": "Верстак",
    "stick": "Палка",
    "oak_planks": "Доски",
    "coal": "Уголь",
    "charcoal": "Древесный уголь",
    "iron_pickaxe": "Железная кирка",
    "iron_sword": "Железный меч",
    "bow": "Лук",
    "furnace": "Печь",
    "chest": "Сундук",
    "bed": "Кровать",
}


def mob_name_ru(mob_id: str) -> str:
    return MOB_NAMES_RU.get(mob_id, mob_id.title())


def item_name_ru(item_en: str) -> str:
    key = item_en.lower().strip()
    return ITEM_NAMES_RU.get(key, item_en)


def recipe_name_ru(recipe_id: str) -> str:
    return RECIPE_NAMES_RU.get(recipe_id, recipe_id.replace("_", " ").title())
